import React from 'react';
import { motion } from 'framer-motion';
import { BrainCircuit, Target, Route, FileCode2, Cpu, BarChart3 } from 'lucide-react';

export default function FeaturesSection() {
  const container = {
    hidden: { opacity: 0 },
    show: { opacity: 1, transition: { staggerChildren: 0.1 } }
  };
  const item = {
    hidden: { opacity: 0, y: 30 },
    show: { opacity: 1, y: 0, transition: { duration: 0.6 } }
  };

  const features = [
    {
      i: <BrainCircuit className="w-8 h-8 text-indigo-400" />,
      t: 'Skill DNA Profile',
      d: 'Deep AI analysis of your resume extracts mastered skills (green), emerging skills (amber), and growth opportunities (red). Displays as a visual distribution with progress bars and percentages. Powered by multi-provider AI.',
      ex: <div className="flex gap-4 mt-2 font-bold text-xs"><span className="text-emerald-500">Mastered 33%</span><span className="text-amber-500">Emerging 50%</span><span className="text-rose-500">Growth 17%</span></div>,
      tag: 'AI POWERED',
      wide: true
    },
    {
      i: <Target className="w-8 h-8 text-indigo-400" />,
      t: 'Career Simulator',
      d: 'Predicts your readiness % for any target role (e.g. "Frontend Developer — 25% Ready"). Identifies Critical Skill Gaps: JavaScript, CSS/Tailwind, Git, Testing (Jest).',
      tag: 'PREDICTIVE'
    },
    {
      i: <Route className="w-8 h-8 text-indigo-400" />,
      t: 'AI Learning Roadmap',
      d: 'Week-by-week personalized learning paths generated by Gemini/GPT/Groq. Rendered as interactive dependency graphs via React Flow.',
      tag: 'MULTI-AI'
    },
    {
      i: <FileCode2 className="w-8 h-8 text-indigo-400" />,
      t: 'Parser & Analyzer',
      d: 'Drag-and-drop upload for PDF, TXT files. Server-side parsing via pdf-parse automatically extracts skills, experience, and feeds the AI pipeline.',
      tag: 'BACKEND'
    },
    {
      i: <Cpu className="w-8 h-8 text-indigo-400" />,
      t: 'Engineering Sim Studio',
      d: 'Full mock interview engine: "Launch Q&A Matrix" and "Start Session" modes. Deep-state architecture assessments with high-density technical evaluation. Architectural reasoning, system design, and behavioral rounds.',
      ex: <div className="flex gap-2 mt-2"><span className="text-[10px] uppercase font-bold text-violet-400 border border-violet-500/30 px-2 py-1 rounded">STUDIO MATRIX 3.5</span><span className="text-[10px] uppercase font-bold text-emerald-400 border border-emerald-500/30 px-2 py-1 rounded">PRODUCTION GRADE</span></div>,
      tag: 'INTERVIEW PREP',
      wide: true
    },
    {
      i: <BarChart3 className="w-8 h-8 text-indigo-400" />,
      t: 'Readiness Dashboard',
      d: 'Real-time: Match Rate 72%, Skill Confidence 65%, ETA: Ready badge. Circular progress indicator (67% — orange ring). Predicted completion timeline.',
      tag: 'REAL-TIME'
    }
  ];

  return (
    <section className="py-24 max-w-7xl mx-auto px-6" id="features">
      <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={item} className="text-center mb-16">
        <div className="flex items-center justify-center gap-2 text-indigo-500 font-bold uppercase tracking-widest text-xs mb-4">
          <span>&mdash;</span> Platform Features
        </div>
        <h2 className="text-3xl md:text-5xl font-black mb-6" style={{ fontFamily: "'Syne', sans-serif" }}>
          Every Tool to Close Your Skill Gap
        </h2>
      </motion.div>

      <motion.div variants={container} initial="hidden" whileInView="show" viewport={{ once: true }} className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {features.map((f, i) => (
          <motion.div key={i} variants={item} whileHover={{ y: -10, boxShadow: '0 24px 48px rgba(139,92,246,0.25)', borderColor: 'rgba(139,92,246,0.4)' }} transition={{ type: 'spring', stiffness: 300, damping: 20 }} className={`group flex flex-col p-8 rounded-3xl bg-slate-900/40 backdrop-blur-md border border-white/10 ${f.wide ? 'md:col-span-2' : ''}`}>
            <motion.div className="w-16 h-16 bg-indigo-500/10 rounded-2xl flex items-center justify-center mb-6" transition={{ type: 'spring', stiffness: 300, damping: 20 }} variants={{ hover: { y: -6, rotate: 10, scale: 1.15 } }}>
              {f.i}
            </motion.div>
            <h3 className="text-2xl font-black mb-3 text-white" style={{ fontFamily: "'Syne', sans-serif" }}>{f.t}</h3>
            <p className="text-slate-400 text-sm leading-relaxed mb-4">{f.d}</p>
            {f.ex && <div className="mb-6">{f.ex}</div>}
            <div className="mt-auto self-start bg-white/5 border border-white/10 px-3 py-1 rounded-md text-[10px] font-bold text-slate-400 uppercase tracking-widest">
              {f.tag}
            </div>
          </motion.div>
        ))}
      </motion.div>
    </section>
  );
}
